"""article ai summaries and meta fetch

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 07:08:18.652735
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('ai_summary_en', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('ai_summary_es', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('meta_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'meta_fetched_at')
    op.drop_column('articles', 'ai_summary_es')
    op.drop_column('articles', 'ai_summary_en')
    # ### end Alembic commands ###
