"""spanish texts, anonymous users and feedback

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 07:38:46.620178
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_feedback',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'article_id')
    )
    op.add_column('articles', sa.Column('title_es', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('topics_es', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('hn_comments', sa.Column('text_es', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('anon_token_hash', sa.String(length=64), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('users_anon_token_hash_key', 'users', ['anon_token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('users_anon_token_hash_key', 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'anon_token_hash')
    op.drop_column('hn_comments', 'text_es')
    op.drop_column('articles', 'topics_es')
    op.drop_column('articles', 'title_es')
    op.drop_table('article_feedback')
    # ### end Alembic commands ###
