"""hacker news front page day and rank

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 08:15:19.450135
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('hn_front_day', sa.Date(), nullable=True))
    op.add_column('articles', sa.Column('hn_front_rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'hn_front_rank')
    op.drop_column('articles', 'hn_front_day')
    # ### end Alembic commands ###
