"""article lead image

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05 09:31:06.606541
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'image_url')
    # ### end Alembic commands ###
