"""digest kinds

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 12:11:30.970860
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('kind', sa.String(length=16), server_default='general', nullable=False))
    op.drop_index(op.f('ix_digests_created_at'), table_name='digests')
    op.create_index('ix_digests_kind_created_at', 'digests', ['kind', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_digests_kind_created_at', table_name='digests')
    op.create_index(op.f('ix_digests_created_at'), 'digests', ['created_at'], unique=False)
    op.drop_column('digests', 'kind')
    # ### end Alembic commands ###
