"""digest bullets

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-05 14:21:46.449146
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digests', sa.Column('bullets_en', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.add_column('digests', sa.Column('bullets_es', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digests', 'bullets_es')
    op.drop_column('digests', 'bullets_en')
    # ### end Alembic commands ###
