import { createContext, useContext } from "react";
import type { Lang } from "./types";

const es = {
  langGroup: "Idioma",
  themeGroup: "Tema",
  themeLight: "Claro",
  themeDark: "Oscuro",
  themeSystem: "Automático",
  code: "Código",
  dateline: (total: string, enriched: string) =>
    `${total} noticias de Reuters, Ars Technica y Hacker News; Gemini ha resumido y traducido ${enriched}.`,
  important: "Lo importante hoy",
  latest: "Última hora",
  filterSource: "Filtrar por fuente",
  filterSection: "Filtrar por sección",
  all: "Todo",
  allOf: (source: string) => `Todo ${source}`,
  today: "Hoy",
  frontOf: (day: string) => `Portada de Hacker News del ${day}`,
  yesterday: "Ayer",
  minutesAgo: (n: number) => `hace ${n} min`,
  hoursAgo: (n: number) => `hace ${n} h`,
  daysAgo: (n: number) => `hace ${n} d`,
  points: (n: number) => `${n} ${n === 1 ? "punto" : "puntos"}`,
  comments: (n: number) => `${n} ${n === 1 ? "comentario" : "comentarios"}`,
  hideComments: "Ocultar discusión",
  replies: (n: number) => `${n} ${n === 1 ? "respuesta" : "respuestas"}`,
  deleted: "[eliminado]",
  like: "Me interesa",
  dislike: "No me interesa",
  feedbackHint: "Tus valoraciones entrenarán tu feed «Para ti»",
  feedbackError: "No se guardó la valoración",
  loadingNews: "Cargando noticias…",
  loadMore: "Cargar noticias anteriores",
  emptySource: "Aún no hay noticias aquí. Se actualizan cada 5 minutos.",
  feedError: (e: string) => `No se pudo cargar el feed: ${e}.`,
  retry: "Reintentar",
  loadingDiscussion: "Cargando y traduciendo la discusión…",
  loadingDiscussionEn: "Cargando la discusión…",
  discussionError: (e: string) => `No se pudo cargar la discusión: ${e}.`,
  noComments: "Este hilo todavía no tiene comentarios.",
  openOnHN: "Abrir el hilo en Hacker News",
  translatedNote: "Comentarios traducidos automáticamente con Gemini.",
  showOriginal: "Ver originales",
  showTranslation: "Ver traducción",
  untranslated: "Sin traducir todavía",
  discussionTitle: "Discusión en Hacker News",
  close: "Cerrar",
  colophon:
    "MyNews es código abierto con licencia MIT. Los titulares traducidos, las descripciones y la traducción de comentarios los genera Gemini y pueden contener errores: la noticia completa está siempre en su web original.",
};

type Dict = typeof es;

const en: Dict = {
  langGroup: "Language",
  themeGroup: "Theme",
  themeLight: "Light",
  themeDark: "Dark",
  themeSystem: "Automatic",
  code: "Code",
  dateline: (total, enriched) =>
    `${total} stories from Reuters, Ars Technica and Hacker News; Gemini has summarised and translated ${enriched}.`,
  important: "Today's essentials",
  latest: "Latest",
  filterSource: "Filter by source",
  filterSection: "Filter by section",
  all: "All",
  allOf: (source) => `All ${source}`,
  today: "Today",
  frontOf: (day) => `Hacker News front page, ${day}`,
  yesterday: "Yesterday",
  minutesAgo: (n) => `${n} min ago`,
  hoursAgo: (n) => `${n} h ago`,
  daysAgo: (n) => `${n} d ago`,
  points: (n) => `${n} ${n === 1 ? "point" : "points"}`,
  comments: (n) => `${n} ${n === 1 ? "comment" : "comments"}`,
  hideComments: "Hide discussion",
  replies: (n) => `${n} ${n === 1 ? "reply" : "replies"}`,
  deleted: "[deleted]",
  like: "Interested",
  dislike: "Not interested",
  feedbackHint: "Your ratings will train your For You feed",
  feedbackError: "Rating not saved",
  loadingNews: "Loading stories…",
  loadMore: "Load earlier stories",
  emptySource: "No stories here yet. They are refreshed every 5 minutes.",
  feedError: (e) => `Couldn't load the feed: ${e}.`,
  retry: "Retry",
  loadingDiscussion: "Loading discussion…",
  loadingDiscussionEn: "Loading discussion…",
  discussionError: (e) => `Couldn't load the discussion: ${e}.`,
  noComments: "This thread has no comments yet.",
  openOnHN: "Open the thread on Hacker News",
  translatedNote: "Comments machine-translated with Gemini.",
  showOriginal: "Show originals",
  showTranslation: "Show translation",
  untranslated: "Not translated yet",
  discussionTitle: "Hacker News discussion",
  close: "Close",
  colophon:
    "MyNews is open source under the MIT licence. Translated headlines, descriptions and comment translations are generated by Gemini and may contain mistakes: the full story is always on the original site.",
};

export const DICTS: Record<Lang, Dict> = { es, en };

export const SECTION_LABEL: Record<string, Record<Lang, string>> = {
  world: { es: "Mundo", en: "World" },
  technology: { es: "Tecnología", en: "Technology" },
  ai: { es: "IA", en: "AI" },
  "biz-it": { es: "Biz & IT", en: "Biz & IT" },
  security: { es: "Seguridad", en: "Security" },
  front: { es: "Portada", en: "Front page" },
};

export const LangContext = createContext<Lang>("es");
export const useLang = () => useContext(LangContext);
export const useT = () => DICTS[useLang()];
